language: java
jdk: oraclejdk8

script:
  - ./gradlew check -x signArchives
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

branches:
  only:
  - master
  - /^RELEASE-.*$/

sudo: required
